spring.application.name=assistant-recipe-ai
spring.datasource.url=jdbc:postgresql://localhost:5432/recipe_db
spring.datasource.username=admin
spring.datasource.password=Recass123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true


server=8080

ai.ollama.url=http://localhost:11434
ai.ollama.model=llama2.3:2b

